name: Deploy

on:
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: SCP Command to Transfer Files
        uses: appleboy/scp-action@v0.1.1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          password: ${{ secrets.PASSWORD }}
          source: "."
          target: "/home/ci/app"

      - name: SSH Remote Commands
        uses: appleboy/ssh-action@master
        env:
          DB_USER: "MY-DB-USER"
          TEST: ${{ secrets.PASSWORD }}
        with:
          envs: DB_USER
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          debug: true
          script: |
            echo "test"
            echo $DB_USER
            echo $TEST
            docker-compose config

          # export MYSQL_DATABASE=$DB_DATABASE
          # composer install
          # docker-compose config
          # docker-compose up -d --build --force-recreate
          # docker exec -d ci-php bin/console d:m:m